export type Liquors = 'Vodka' | 'Tequila' | 'Gin';
export type Flavours = 'Sweet' | 'Sour' | 'Spicy';

export type Drink = {
	id: number;
	name: string;
	liquor: Liquors;
	flavour: Flavours;
	rating: number;
	steps: string[];
	detailed_steps: string[];
	style: string;
	time: string;
	difficulty: 'Easy' | 'Medium' | 'Hard';
	ingredients: (
		| 'Vodka'
		| 'Tequila'
		| 'Gin'
		| 'Lime juice'
		| 'Soda water'
		| 'Simple syrup'
		| 'Ice'
		| 'Mint'
	)[];
	tools: string[];
	image: string;
	strength: 'Light' | 'Moderate' | 'Strong';
	colour: string;
};

export const liquors = ['Vodka', 'Tequila', 'Gin'];

export const ingredients = ['Lime juice', 'Simple syrup', 'Soda water', 'Mint', 'Ice'];

export const drinksData: Drink[] = [
	{
		id: 1,
		name: 'Citrus Spark',
		liquor: 'Vodka',
		flavour: 'Sour',
		rating: 4,
		colour: 'Deep',
		strength: 'Moderate',
		steps: [
			'Add vodka and lime juice',
			'Strain into a chilled glass',
			'Top with soda water',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Measure 50ml of vodka and 25ml of lime juice using a jigger and pour them into a shaker.',
			'Shake vigorously for about 10 seconds to blend and chill the drink.',
			'Strain the mixture into a chilled glass filled halfway with ice.',
			'Top off with soda water, give a gentle stir with a bar spoon, and garnish with a fresh mint leaf.',
		],
		style: 'Refreshing',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Lime juice', 'Soda water', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass', 'Bar spoon'],
		image: 'https://images.unsplash.com/photo-1549746423-e5fe9cafded8?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 2,
		name: 'Fiery Agave',
		liquor: 'Tequila',
		flavour: 'Spicy',
		rating: 5,
		colour: 'Deep',
		strength: 'Strong',
		steps: [
			'Add tequila, lime juice, and simple syrup',
			'Shake with ice',
			'Strain into a glass',
			'Garnish with mint',
		],
		detailed_steps: [
			'Combine 50ml tequila, 20ml lime juice, and 10ml simple syrup in a shaker.',
			'Add ice until the shaker is about three-quarters full.',
			'Shake firmly for 10–15 seconds until chilled and slightly frothy.',
			'Strain the mixture into a clean glass over fresh ice.',
			'Finish with a mint leaf for aroma and a touch of freshness.',
		],
		style: 'Bold',
		time: '6 mins',
		difficulty: 'Easy',
		ingredients: ['Tequila', 'Lime juice', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass', 'Jigger'],
		image: 'https://images.unsplash.com/photo-1550512358-5c497af22d15?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 3,
		name: 'Sweet Blossom',
		liquor: 'Gin',
		flavour: 'Sweet',
		rating: 3,
		colour: 'Clear',
		strength: 'Light',
		steps: ['Add gin and simple syrup', 'Shake on ice', 'Strain into a glass', 'Top with soda water'],
		detailed_steps: [
			'Pour 45ml of gin and 15ml of simple syrup into a shaker.',
			'Fill the shaker with ice and shake for 8–10 seconds to chill.',
			'Strain the mixture into a glass filled with fresh ice.',
			'Top off with soda water and give a light stir for balance.',
		],
		style: 'Elegant',
		time: '4 mins',
		difficulty: 'Hard',
		ingredients: ['Gin', 'Simple syrup', 'Soda water', 'Ice'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1668771899398-1cdd763f745e?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 4,
		name: 'Tequila Ember',
		liquor: 'Tequila',
		flavour: 'Spicy',
		rating: 4,
		colour: 'Deep',
		strength: 'Strong',
		steps: [
			'Add tequila, simple syrup, and soda water',
			'Shake on ice',
			'Strain into a glass',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Measure 50ml tequila and 15ml simple syrup into a shaker.',
			'Add ice and shake for about 10 seconds until cold.',
			'Strain into a clean glass filled with ice cubes.',
			'Top with soda water and gently stir to combine.',
			'Add a mint leaf on top for a fresh finish.',
		],
		style: 'Bold',
		time: '7 mins',
		difficulty: 'Easy',
		ingredients: ['Tequila', 'Simple syrup', 'Soda water', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1679075335374-c7a0d7e4ef15?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 5,
		name: 'Frosted Citrus',
		liquor: 'Vodka',
		flavour: 'Sour',
		rating: 5,
		colour: 'Clear',
		strength: 'Light',
		steps: [
			'Add vodka, lime juice, and simple syrup',
			'Shake on ice',
			'Strain into a glass',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Add 50ml vodka, 20ml lime juice, and 15ml simple syrup to a shaker.',
			'Add plenty of ice to the shaker and shake for 12 seconds.',
			'Strain into a chilled glass filled with ice.',
			'Place a mint leaf on top for garnish and aroma.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Lime juice', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1687354256687-b5ee47c043c1?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 6,
		name: 'Sweet Drift',
		liquor: 'Gin',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Clear',
		strength: 'Light',
		steps: [
			'Add gin, soda water, and simple syrup',
			'Stir gently with ice',
			'Serve in a glass',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Pour 45ml gin, 15ml simple syrup, and 100ml soda water into a mixing glass.',
			'Add ice and stir gently with a bar spoon to combine.',
			'Strain into a clean glass with a few ice cubes.',
			'Finish with a mint leaf garnish for freshness.',
		],
		style: 'Elegant',
		time: '4 mins',
		difficulty: 'Easy',
		ingredients: ['Gin', 'Simple syrup', 'Soda water', 'Ice', 'Mint'],
		tools: ['Shaker', 'Bar spoon', 'Glass'],
		image: 'https://images.unsplash.com/photo-1453824979084-c8fd42932378?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 7,
		name: 'Smoky Citrus',
		liquor: 'Tequila',
		flavour: 'Sour',
		rating: 3,
		colour: 'Deep',
		strength: 'Moderate',
		steps: [
			'Add tequila, lime juice, and soda water',
			'Shake on ice',
			'Strain into a glass',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Combine 50ml tequila and 20ml lime juice in a shaker.',
			'Add a scoop of ice and shake for 10 seconds to blend flavors.',
			'Strain into a chilled glass filled with fresh ice.',
			'Top off with soda water and stir lightly.',
			'Add a mint leaf for a crisp aroma.',
		],
		style: 'Refreshing',
		time: '6 mins',
		difficulty: 'Medium',
		ingredients: ['Tequila', 'Lime juice', 'Soda water', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1635547018520-043b6f0e1a36?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 8,
		name: 'Spiced Garden',
		liquor: 'Gin',
		flavour: 'Spicy',
		rating: 5,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: [
			'Add gin, lime juice, and simple syrup',
			'Shake with ice',
			'Strain into a glass',
			'Garnish with mint leaf',
		],
		detailed_steps: [
			'Add 50ml gin, 15ml lime juice, and 10ml simple syrup to a shaker.',
			'Add ice cubes and shake well for 10 seconds.',
			'Strain into a chilled glass with fresh ice.',
			'Garnish with a mint leaf for a hint of freshness and color.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Gin', 'Lime juice', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1661344277834-bde1f854ec10?auto=format&fit=crop&w=800&q=80',
	},
	{
		id: 9,
		name: 'Tropical Breeze',
		liquor: 'Vodka',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add vodka and lime juice', 'Shake with ice', 'Strain into a glass', 'Garnish with mint'],
		detailed_steps: [
			'Measure 50ml vodka and 25ml lime juice into a shaker.',
			'Add ice and shake for 10 seconds until chilled.',
			'Strain into a glass filled with ice.',
			'Garnish with a sprig of mint.',
		],
		style: 'Refreshing',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1691939610599-a9a3dde8e810?q=80&w=425&auto=format&fit=crop',
	},
	{
		id: 10,
		name: 'Berry Blast',
		liquor: 'Vodka',
		flavour: 'Sweet',
		rating: 5,
		colour: 'Deep',
		strength: 'Moderate',
		steps: ['Add vodka and simple syrup', 'Shake with ice', 'Strain', 'Top with soda water'],
		detailed_steps: [
			'Measure 50ml vodka and 15ml simple syrup into a shaker.',
			'Fill the shaker with ice and shake for 12 seconds.',
			'Strain into a chilled glass with ice.',
			'Top with soda water and stir gently.',
		],
		style: 'Refreshing',
		time: '5 mins',
		difficulty: 'Easy',
		ingredients: ['Vodka', 'Simple syrup', 'Ice', 'Soda water'],
		tools: ['Shaker', 'Strainer', 'Glass', 'Bar spoon'],
		image: 'https://images.unsplash.com/photo-1500217052183-bc01eee1a74e?q=80&w=388&auto=format&fit=crop',
	},
	{
		id: 11,
		name: 'Spicy Citrus',
		liquor: 'Tequila',
		flavour: 'Spicy',
		rating: 4,
		colour: 'Vibrant',
		strength: 'Strong',
		steps: ['Add tequila and lime juice', 'Shake with ice', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml tequila and 20ml lime juice in a shaker.',
			'Add ice and shake vigorously for 10 seconds.',
			'Strain into a chilled glass.',
			'Garnish with a mint leaf for aroma.',
		],
		style: 'Bold',
		time: '6 mins',
		difficulty: 'Medium',
		ingredients: ['Tequila', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1609951651556-5334e2706168?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 12,
		name: 'Cucumber Cooler',
		liquor: 'Gin',
		flavour: 'Spicy',
		rating: 3,
		colour: 'Clear',
		strength: 'Light',
		steps: ['Add gin and lime juice', 'Shake with ice', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Pour 50ml gin and 25ml lime juice into a shaker.',
			'Add ice and shake gently for 8–10 seconds.',
			'Strain into a glass over fresh ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Bold',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Gin', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1675949335489-f778abf84197?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 13,
		name: 'Citrus Fire',
		liquor: 'Tequila',
		flavour: 'Sour',
		rating: 5,
		colour: 'Deep',
		strength: 'Strong',
		steps: ['Add tequila and lime juice', 'Shake with ice', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml tequila and 20ml lime juice in a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a glass filled with ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Eloquent',
		time: '6 mins',
		difficulty: 'Hard',
		ingredients: ['Tequila', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1592858167090-2473780d894d?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 14,
		name: 'Peach Delight',
		liquor: 'Vodka',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add vodka and simple syrup', 'Shake', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Add 50ml vodka and 15ml simple syrup into a shaker.',
			'Add ice and shake for 12 seconds.',
			'Strain into a chilled glass.',
			'Garnish with a mint leaf.',
		],
		style: 'Bold',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=870&auto=format&fit=crop',
	},
	{
		id: 15,
		name: 'Tangerine Twist',
		liquor: 'Tequila',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add tequila and lime juice', 'Shake', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Measure 50ml tequila and 25ml lime juice into a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a glass with ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Refreshing',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Tequila', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image:
			'https://plus.unsplash.com/premium_photo-1675667381451-be2fc08a122e?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 16,
		name: 'Lavender Lemon',
		liquor: 'Gin',
		flavour: 'Sweet',
		rating: 5,
		colour: 'Clear',
		strength: 'Strong',
		steps: ['Add gin and simple syrup', 'Shake', 'Strain', 'Top with soda', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml gin and 15ml simple syrup in a shaker.',
			'Add ice and shake lightly for 8 seconds.',
			'Strain into a glass filled with ice.',
			'Top with soda water and garnish with a mint leaf.',
		],
		style: 'Refreshing',
		time: '6 mins',
		difficulty: 'Easy',
		ingredients: ['Gin', 'Simple syrup', 'Ice', 'Soda water', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass', 'Bar spoon'],
		image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=472&auto=format&fit=crop',
	},
	{
		id: 17,
		name: 'Ruby Sunset',
		liquor: 'Gin',
		flavour: 'Spicy',
		rating: 4,
		colour: 'Deep',
		strength: 'Strong',
		steps: ['Add gin and simple syrup', 'Shake', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Measure 50ml gin and 15ml simple syrup into a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a chilled glass with ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Gin', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 18,
		name: 'Cranberry Kiss',
		liquor: 'Vodka',
		flavour: 'Spicy',
		rating: 3,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add vodka and simple syrup', 'Shake', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml vodka and 15ml simple syrup in a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a chilled glass with ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Easy',
		ingredients: ['Vodka', 'Simple syrup', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?q=80&w=464&auto=format&fit=crop',
	},
	{
		id: 19,
		name: 'Mango Mojito',
		liquor: 'Gin',
		flavour: 'Sweet',
		rating: 5,
		colour: 'Vibrant',
		strength: 'Light',
		steps: ['Muddle mint', 'Add gin and simple syrup', 'Shake', 'Strain', 'Top with soda'],
		detailed_steps: [
			'Muddle fresh mint leaves in a shaker.',
			'Add 50ml gin and 15ml simple syrup.',
			'Add ice and shake gently for 10 seconds.',
			'Strain into a glass and top with soda water.',
		],
		style: 'Elegant',
		time: '6 mins',
		difficulty: 'Easy',
		ingredients: ['Gin', 'Mint', 'Simple syrup', 'Ice', 'Soda water'],
		tools: ['Shaker', 'Muddler', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=464&auto=format&fit=crop',
	},
	{
		id: 20,
		name: 'Lime Cooler',
		liquor: 'Gin',
		flavour: 'Sour',
		rating: 4,
		colour: 'Deep',
		strength: 'Light',
		steps: ['Add gin and lime juice', 'Shake', 'Strain', 'Top with soda', 'Garnish with mint'],
		detailed_steps: [
			'Measure 50ml gin and 25ml lime juice into a shaker.',
			'Add ice and shake for 8 seconds.',
			'Strain into a glass filled with ice.',
			'Top with soda water and garnish with a mint leaf.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Gin', 'Lime juice', 'Soda water', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1560526860-1f0e56046c85?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 21,
		name: 'Ginger Fizz',
		liquor: 'Vodka',
		flavour: 'Spicy',
		rating: 3,
		colour: 'Clear',
		strength: 'Moderate',
		steps: ['Add vodka and simple syrup', 'Shake', 'Strain', 'Top with soda'],
		detailed_steps: [
			'Combine 50ml vodka and 15ml simple syrup in a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a glass filled with ice.',
			'Top with soda water and stir gently.',
		],
		style: 'Bold',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Simple syrup', 'Ice', 'Soda water'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?q=80&w=415&auto=format&fit=crop',
	},
	{
		id: 22,
		name: 'Tropical Sunset',
		liquor: 'Vodka',
		flavour: 'Sour',
		rating: 5,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add vodka and lime juice', 'Shake', 'Strain', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml vodka and 25ml lime juice in a shaker.',
			'Add ice and shake for 12 seconds.',
			'Strain into a chilled glass with ice.',
			'Garnish with a mint leaf.',
		],
		style: 'Elegant',
		time: '5 mins',
		difficulty: 'Medium',
		ingredients: ['Vodka', 'Lime juice', 'Ice', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?q=80&w=387&auto=format&fit=crop',
	},
	{
		id: 23,
		name: 'Peach Fizz',
		liquor: 'Gin',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Deep',
		strength: 'Light',
		steps: ['Add gin and simple syrup', 'Shake', 'Strain', 'Top with soda', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml gin and 15ml simple syrup in a shaker.',
			'Add ice and shake for 8 seconds.',
			'Strain into a glass with ice.',
			'Top with soda water and garnish with a mint leaf.',
		],
		style: 'Bold',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Gin', 'Simple syrup', 'Ice', 'Soda water', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=869&auto=format&fit=crop',
	},
	{
		id: 24,
		name: 'Cherry Spark',
		liquor: 'Vodka',
		flavour: 'Sweet',
		rating: 4,
		colour: 'Vibrant',
		strength: 'Moderate',
		steps: ['Add vodka and simple syrup', 'Shake', 'Strain', 'Top with soda', 'Garnish with mint'],
		detailed_steps: [
			'Combine 50ml vodka and 15ml simple syrup in a shaker.',
			'Add ice and shake for 10 seconds.',
			'Strain into a chilled glass with ice.',
			'Top with soda water and garnish with a mint leaf.',
		],
		style: 'Bold',
		time: '5 mins',
		difficulty: 'Hard',
		ingredients: ['Vodka', 'Simple syrup', 'Ice', 'Soda water', 'Mint'],
		tools: ['Shaker', 'Strainer', 'Glass'],
		image: 'https://images.unsplash.com/photo-1587888637140-849b25d80ef9?q=80&w=387&auto=format&fit=crop',
	},
];
